### PR TITLE
Update FDS+EVAC_Guide.tex

### PR DESCRIPTION
**Pull request by godisreal**

### CODE REVIEW

**Comment by godisreal** [comment]
Hi, Timo, 
I suppose that users can set up how agents select the doors and exits by using "AGENT_TYPE", "KNOWN_DOOR_NAMES" and "KNOWN_DOOR_PROB".  Is there any other parameters in the user input file that may directly change the door selection result?   
Best Regards, 
Peng WANG

**Comment by tkorhon1** [comment]
Hi Peng,

Yes, those are the main parameters. There are some smoke related paramters that
have some effect (which door is considered to be smoke free and which is not).
These are described in the manual elsewhere. No need to write anything about
these parameters here, because they are details (and the default values are
good enough usually).

**Comment by godisreal** [comment]
Hi, Timo, any suggestion about the above changes?  Is my input helpful or not?  
Also, if you do not want changes directly merged into your master branch, you may add a branch there.  Please let me know your preference.  Thanks.

**Comment by godisreal** [comment]
Also a known door is also mentioned as a familiar door?  
In the manual both terms are widely used when you introduce how new types of agents select doors and exits.  However, I suppose they are exactly the same thing thing in your algorithm.

**Comment by tkorhon1** [comment]
Yes, they are exactly same thing (known door vs familiar door). Familiar would be a better word. But I used a keyword KNOWN_DOOR when I first programmed the source code. So, it would need some programming effort to change this to FAMILIAR_DOOR. Well, not much, but one should also make a check for the old input work KNOWN_DOOR so that the code would be backward compatible.

And I would like you to change directly the fds+evac manual LaTeX source code here:
https://github.com/tkorhon1/FDS-Evac-Guide

So, the LaTeX source in the fds/Manuals/FDS_Evacuation_Guide is only updated by me.
I will make my changes together with you to "tkorhon1/FDS-Evac-Guide". And at some
point (probably, when I update the V&V figures, i.e., rerun the V&V cases), I will update
the "fds/Manuals/FDS_Evacuation_Guide" LaTeX source.

TimoK

**Comment by godisreal** [comment]
Hi, Timo, 
OK.  I may go on with Section 3.5 (Door Selection Algorithm).  I read the section several times and browse the code in the meantime.  Some concepts (e.g, known door or familiar door) confused me much until I found some clue in your programming code.  I think there are some issues beyond the langugage and writing, and thus I am trying to figure out how the door selection algorithm exactly works for various scenarios.   
Best Regards

**Comment by tkorhon1** [comment]
Thanks,
Timo

**Pull request merged**
