### PR TITLE
Update evac.f90:  About TPRE Feature of Herding Agents

### PR DESCRIPTION
**Pull request by godisreal**
I modified one's tpre with surrounding agents' tpre.  The model is based on opinion dynamics.  
I've tested this modification in FDS6.5.3 and it is a useful feature.  So you may also try it in the latest version.  Your comments are much welcome.

### CODE REVIEW

**Comment by tkorhon1** [comment]
Well, I should check this at some point. This could be easily added.

**Comment by godisreal** [comment]
I am glad to know that you have merged this pull request.  
I think a document is also necessary to explain the model and algorithm.  
Below is a brief discription of the model.  Your comments are much welcome.  
Merry Christmas!


**Herding Effect and Opinion Dynamics**

Herding is especially evident when people are responding to an emergency. Emergency implies time-pressure and excessive time-pressure weakens the ability of logical thinking and reasoning, and independent decision making is more difficult in stressful conditions. Thus, people are more inclined to follow others (e.g., neighbors' decisions) rather than make decisions by themselves. This effect is characterized by an existing model in opinion dynamics as below.   

vi0(t+1)=(1-pi )vi0(t) + pi vj0(t)     (Eq.6)

The desired velocity vi0 is updated by mixing itself with another individual's desired velocity vj0. Both options are weighted with some parameter (1-pi) and pi , and two options follow two-point distribution with probability (1-pi) and pi , and vi0 is updated by the statistical average. As a consequence, an individual keeps his own opinion if pi is low whereas follows others if pi is high. An important issue relates to the meaning of parameter pi and how it evolves in the simulation. In a statistical sense pi means probability that individual expects to follow others. In Helbing, Farkas and Vicsek, 2000, pi is considered to indicate one's panic level, and it is given by ratio of (vi0 - vi )/vi0, and it is called a “nervousness" parameter. This ratio critically affects several testing results in their work, and it has been applied in FDS+Evac (Korhonen, 2017). 

In this paper we will apply opinion dynamics to modeling pre-evacuation behavior of crowd. The pre-evacuation time of each individual agent is updated by Equation (7).

tpre_i( t+1)=(1-pi)tpre_i(t )+pi tpre_others(t)    (Eq. 7)

The pre-evacuation time of an individual tpre_i is updated by mixing itself with the average pre-evacuation time of surrounding ones within radius Ri. Both options are weighted with some parameter (1-pi) and pi , and two options follow twopoint distribution with probability (1-pi) and pi , and tpre_i is updated by the statistical average. As a result, individualistic behavior is dominant if pi is low whereas herding behavior dominates if pi is high.

**Comment by tkorhon1** [comment]
Well, I have actually commented your addition out in my own evac_timo.f90, which I use to generate the evac.f90 that is in GitHub:

                         IF (I_TMP /= 0 .AND. HR%I_Door_Mode == 0) THEN
                            !Timo: IF (I_TMP /= 0) THEN


                            !Timo: HR%TPRE = 0.5_EB*HR%TPRE + 0.5_EB*Other_TPRE
                            HR%TPRE = DT_GROUP_DOOR

The problem is that this should work also for single agents (the normal case in FDS+Evac). So, your group stuff will not change the normal FDS+Evac calculation, where no groups are defined.

So, one should add an IF statement that test if the agent is a part of a group. Well, your code is modifying the herding agent behaviour. So, it might be that the code is not doing what you want.

The current agent (that is using herding algorithm) looks the nearest neighbour agents around. And these nearest neighbour agents might already walk towards exits. Then their TPRE < T (and might be much smaller, e.g. DT_GROUP_DOOR = 0.1s) => your TPRE averaging is not working. 

So, you should add a test if the other agent is already moving and set the TPRE of the moving agents equal to zero seconds in the averaging process. 

And I'll make the pi as an user input on the PERS namelist, say HERDING_TPRE_PROB.
         
                            IF (HERDING_TPRE_PROB > TWO_EPSILON_EB) THEN
                               !HR%TPRE = 0.5_EB*HR%TPRE + 0.5_EB*Other_TPRE
                               HR%TPRE = (1.0_EB-HERDING_TPRE_PROB)*HR%TPRE + HERDING_TPRE_PROB*Other_TPRE
                            ELSE
                               HR%TPRE = DT_GROUP_DOOR ! Original FDS+Evac
                            END IF

Timo

**Comment by godisreal** [comment]
Hi, Timo.  The above method is effective for herding agents, but not for follower agents.  The herding agents' tpre is thus adapted with surrounding agents.  Here I have a question about code.  

>                      HERDING_LIST_DOORS(ABS(HRE%I_Target)) = HERDING_LIST_DOORS(ABS(HRE%I_Target)) + &
>                                  W0_HERDING -((W0_HERDING-WR_HERDING)/R_HERD_HR)*P2P_DIST

What is the algorithm for HERDING_LIST_DOORS?  I think a kind of weight is computed for each door and exit, and I_TMP is the door or exit with the maximal weight.  Is that right?  
I am trying to understand this issue and extend this tpre method for follower agents also.

**Pull request merged**
